In [1]:
import numpy as np


In [2]:
x = np.array([[1,1],[3,3]], dtype = np.float64)
y = np.array([[5,5],[6,6]], dtype = np.float64)

v = np.array([10,10])
w = np.array([20,20])
print(np.dot(x,v))

[20. 60.]


In [3]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(a,'\n')
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[2 3]
 [6 7]]


In [20]:
b[0,0] = 69
print(b,'\n')
print(a)

[[69  3]
 [ 6  7]]
[[ 1 69  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
row_r1 = a[1,:]
print(a,'\n')
print(row_r1, row_r1.shape, '\n')
row_r2 = a[1,1:3]
print(row_r2, row_r2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[5 6 7 8] (4,) 

[6 7] (2,)


In [38]:
a = np.array([[1,2], [3,4], [5,6]])
print(np.array([a[0,0], a[1,1], a[2,0]]))
print(a[[0,1,2], [0,1,0]])
print(a[[1,2], [0,1]])

[1 4 5]
[1 4 5]
[3 6]


In [12]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(a,'\n')
print(a.shape,'\n')
b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b],'\n')
a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

(4, 3) 

[ 1  6  7 11] 

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [17]:
a = np.array([[1,2], [3,4], [5,6]])
print(a,'\n')
bol = (a > 2)
print(bol, '\n')
print(a[bol], '\n')
print(a[a>2])

[[1 2]
 [3 4]
 [5 6]] 

[[False False]
 [ True  True]
 [ True  True]] 

[3 4 5 6] 

[3 4 5 6]


In [21]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(a,'\n')
print(np.sum(a))
print(np.sum(a, axis = 0))
print(np.sum(a, axis = 1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

78
[22 26 30]
[ 6 15 24 33]


In [25]:
x = np.arange(8)
print(x,'\n')
a = np.arange(4).reshape(2,2)
print(a,'\n')
a = np.arange(8).reshape(2,4)
print(a,'\n')
a = np.arange(8).reshape(4,2)
print(a,'\n')
a = np.arange(12).reshape(4,3)
print(a,'\n')
a = np.arange(8).reshape(2,2,2)
print(a,'\n')

[0 1 2 3 4 5 6 7] 

[[0 1]
 [2 3]] 

[[0 1 2 3]
 [4 5 6 7]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 



In [32]:
from numpy import reshape 
from numpy import array 

a = array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
b1 = a.shape[0]
b2 = a.shape[1]
print(b)
c = a.reshape(b2,b1)
print(a)
print(c)

5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [35]:
a = np.array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11]] )
print(a.ndim)
b = np.array([[[0, 1],  [2, 3]], [[4, 5],  [6, 7]]])
print(b.ndim)

2
3


In [37]:
a = np.array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11]] )
print(a,'\n')
print(a.T)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [53]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]] )
print(a,'\n')
x = np.array([1, 1, 1])
b = np.empty_like(a)

for i in range(3):
    b[i, :] = a[i, :] + x
print(b,'\n')

c = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]] )
d = c + x
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
